### ISSUE TITLE
OR search operator

### ISSUE THREAD

**Issue by dvolatility** [ianmaddox/feedsifter#2]
I've been looking for this for a while, thank you. One question: Is there a way to use the OR search operator in the sifter?

**Comment by ianmaddox** [comment]
Each search line is evaluated as an OR to the rest, with negative matches taking priority over positives. Since each line is a regular expression, you get AND functionality by making a compound regex.
Hope this helps!

**Comment by dvolatility** [comment]
Ok I get it now. So basically: sample,free = sample AND free. I was confused because you didn't have an example with a comma. Thanks!

**Comment by ianmaddox** [comment]
Great feedback! I'll update the hint text.
